import ConnectSocial from "@/components/shared/ConnectSocial";
import "./globals.css";

export const metadata = {
  title: "Panavers DAO PSFMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConnectSocial>{children}</ConnectSocial>
      </body>
    </html>
  );
}
